---
repos:
  - repo: https://github.com/paddyroddy/.github
    rev: v0.371.0
    hooks:
      - id: general-hooks
      - id: python-hooks
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 43.3.6
    hooks:
      - id: renovate-config-validator
        args:
          - renovate/default-config.json5
